/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package MTMS;

/**
 *
 * @author hguo87
 */
public class MTMS_GUI extends javax.swing.JFrame {

    /**
     * Creates new form MTMS_GUI
     */
    
    public MTMS_Login fromLogin = null;
    
    public MTMS_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbpMain = new javax.swing.JTabbedPane();
        pnlUserInfo = new javax.swing.JPanel();
        pnlUserBasics = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tbxUserID = new javax.swing.JTextField();
        tbxUserName = new javax.swing.JTextField();
        lblUserRole = new javax.swing.JLabel();
        btnEditBasics = new javax.swing.JButton();
        pnlUserOthers = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbxUserDetails = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btnEditOthers = new javax.swing.JButton();
        pnlPatientOps = new javax.swing.JPanel();
        pnlTestOps = new javax.swing.JPanel();
        pnlUserOps = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblLoginName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome to MTMS!");

        tbpMain.setToolTipText("My Info");

        pnlUserBasics.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("ID:");

        jLabel4.setText("Name:");

        jLabel5.setText("Role:");

        tbxUserID.setText("00000");

        tbxUserName.setText("Guest");

        lblUserRole.setText("Guest");

        btnEditBasics.setText("Edit");

        org.jdesktop.layout.GroupLayout pnlUserBasicsLayout = new org.jdesktop.layout.GroupLayout(pnlUserBasics);
        pnlUserBasics.setLayout(pnlUserBasicsLayout);
        pnlUserBasicsLayout.setHorizontalGroup(
            pnlUserBasicsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlUserBasicsLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlUserBasicsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnlUserBasicsLayout.createSequentialGroup()
                        .add(jLabel3)
                        .add(35, 35, 35)
                        .add(tbxUserID, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .add(pnlUserBasicsLayout.createSequentialGroup()
                        .add(pnlUserBasicsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel4)
                            .add(jLabel5))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(pnlUserBasicsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(pnlUserBasicsLayout.createSequentialGroup()
                                .add(6, 6, 6)
                                .add(lblUserRole))
                            .add(tbxUserName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 461, Short.MAX_VALUE)
                        .add(btnEditBasics))))
        );
        pnlUserBasicsLayout.setVerticalGroup(
            pnlUserBasicsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlUserBasicsLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlUserBasicsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(tbxUserID, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlUserBasicsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(tbxUserName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlUserBasicsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(lblUserRole))
                .addContainerGap(14, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlUserBasicsLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(btnEditBasics)
                .addContainerGap())
        );

        pnlUserOthers.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbxUserDetails.setColumns(20);
        tbxUserDetails.setRows(5);
        tbxUserDetails.setText("This user is a guest.\n\nActually this user is not allowed to log in. \n\n\n\n\nThis message is only shown for testing.");
        jScrollPane1.setViewportView(tbxUserDetails);

        jLabel2.setText("Other Details:");

        btnEditOthers.setText("Edit");

        org.jdesktop.layout.GroupLayout pnlUserOthersLayout = new org.jdesktop.layout.GroupLayout(pnlUserOthers);
        pnlUserOthers.setLayout(pnlUserOthersLayout);
        pnlUserOthersLayout.setHorizontalGroup(
            pnlUserOthersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlUserOthersLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlUserOthersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1)
                    .add(pnlUserOthersLayout.createSequentialGroup()
                        .add(jLabel2)
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlUserOthersLayout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(btnEditOthers))
        );
        pnlUserOthersLayout.setVerticalGroup(
            pnlUserOthersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlUserOthersLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnEditOthers))
        );

        org.jdesktop.layout.GroupLayout pnlUserInfoLayout = new org.jdesktop.layout.GroupLayout(pnlUserInfo);
        pnlUserInfo.setLayout(pnlUserInfoLayout);
        pnlUserInfoLayout.setHorizontalGroup(
            pnlUserInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlUserInfoLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlUserInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(pnlUserOthers, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(pnlUserBasics, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlUserInfoLayout.setVerticalGroup(
            pnlUserInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlUserInfoLayout.createSequentialGroup()
                .add(pnlUserBasics, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlUserOthers, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbpMain.addTab("My Info", pnlUserInfo);

        org.jdesktop.layout.GroupLayout pnlPatientOpsLayout = new org.jdesktop.layout.GroupLayout(pnlPatientOps);
        pnlPatientOps.setLayout(pnlPatientOpsLayout);
        pnlPatientOpsLayout.setHorizontalGroup(
            pnlPatientOpsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 730, Short.MAX_VALUE)
        );
        pnlPatientOpsLayout.setVerticalGroup(
            pnlPatientOpsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 504, Short.MAX_VALUE)
        );

        tbpMain.addTab("Patient Operations", pnlPatientOps);

        org.jdesktop.layout.GroupLayout pnlTestOpsLayout = new org.jdesktop.layout.GroupLayout(pnlTestOps);
        pnlTestOps.setLayout(pnlTestOpsLayout);
        pnlTestOpsLayout.setHorizontalGroup(
            pnlTestOpsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 730, Short.MAX_VALUE)
        );
        pnlTestOpsLayout.setVerticalGroup(
            pnlTestOpsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 504, Short.MAX_VALUE)
        );

        tbpMain.addTab("Test Operations", pnlTestOps);

        org.jdesktop.layout.GroupLayout pnlUserOpsLayout = new org.jdesktop.layout.GroupLayout(pnlUserOps);
        pnlUserOps.setLayout(pnlUserOpsLayout);
        pnlUserOpsLayout.setHorizontalGroup(
            pnlUserOpsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 730, Short.MAX_VALUE)
        );
        pnlUserOpsLayout.setVerticalGroup(
            pnlUserOpsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 504, Short.MAX_VALUE)
        );

        tbpMain.addTab("User Management", pnlUserOps);

        btnLogout.setText("Logout");
        btnLogout.setToolTipText("");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Welcome to our MTMS system!");
        jLabel1.setToolTipText("");

        lblLoginName.setText("Wecome, Guest!");
        lblLoginName.setToolTipText("");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(14, 14, 14)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(lblLoginName)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnLogout)
                .addContainerGap())
            .add(tbpMain)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnLogout)
                    .add(jLabel1)
                    .add(lblLoginName))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tbpMain)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        if (fromLogin == null) return;
        //this.setVisible(false);
        fromLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MTMS_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MTMS_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MTMS_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MTMS_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MTMS_GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditBasics;
    private javax.swing.JButton btnEditOthers;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLoginName;
    private javax.swing.JLabel lblUserRole;
    private javax.swing.JPanel pnlPatientOps;
    private javax.swing.JPanel pnlTestOps;
    private javax.swing.JPanel pnlUserBasics;
    private javax.swing.JPanel pnlUserInfo;
    private javax.swing.JPanel pnlUserOps;
    private javax.swing.JPanel pnlUserOthers;
    private javax.swing.JTabbedPane tbpMain;
    private javax.swing.JTextArea tbxUserDetails;
    private javax.swing.JTextField tbxUserID;
    private javax.swing.JTextField tbxUserName;
    // End of variables declaration//GEN-END:variables
}
